
version: '3'
services:
  mydemo-app:
    image: 716664300589.dkr.ecr.us-east-1.amazonaws.com/mydemo-app:1.0
    ports:
    - 3000:3000
  mongodb:
    image: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=fui
     - MONGO_INITDB_ROOT_PASSWORD=fui123
    volumes:
     - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
     - 8081:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=fui
     - ME_CONFIG_MONGODB_ADMINPASSWORD=fui123
     - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
     - "mongodb"
volumes:
  mongo-data:
    driver: local
